[package]
name = "awsl"
version = "0.1.0"
authors = ["Wu Yufei <me@tespent.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
void = "1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
